[[emoji]]
match = "(Ascension|é˜¿æ£®æ¾)"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emoji]]
match = "(Argentina|é˜¿æ ¹å»·)"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "(Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "(Australia|AUS|Sydney|åœŸæ¾³|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "(Belgium|æ¯”åˆ©æ—¶)"
emoji = "ğŸ‡§ğŸ‡ª"

[[emoji]]
match = "(Brazil|Paulo|GBR|å·´è¥¿|åœ£ä¿ç½—)"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "(Canada|Montreal|Vancouver|CAN|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "(Switzerland|Zurich|ç‘å£«|è‹é»ä¸–)"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "(Germany|DEU|DE|æ³•å…°å…‹ç¦|å¾·)"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "(Denmark|ä¸¹éº¦)"
emoji = "ğŸ‡©ğŸ‡°"

[[emoji]]
match = "(Spain|ESP|è¥¿ç­ç‰™)"
emoji = "ğŸ‡ªğŸ‡¸"

[[emoji]]
match = "(Europe|æ¬§æ´²)"
emoji = "ğŸ‡ªğŸ‡º"

[[emoji]]
match = "(Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº)"
emoji = "ğŸ‡«ğŸ‡®"

[[emoji]]
match = "(France|Paris|FRA|æ³•å›½|å·´é»)"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "(Hungary|åŒˆç‰™åˆ©)"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "(Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾)"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "(Iceland|ISL|å†°å²›)"
emoji = "ğŸ‡®ğŸ‡¸"

[[emoji]]
match = "(New Zealand|æ–°è¥¿å…°|çº½è¥¿å…°)"
emoji = "ğŸ‡³ğŸ‡¿"

[[emoji]]
match = "(Norway|æŒªå¨)"
emoji = "ğŸ‡³ğŸ‡´"

[[emoji]]
match = "(æ›¼å²›|é©¬æ©å²›)"
emoji = "ğŸ‡®ğŸ‡²"

[[emoji]]
match = "(Israel|ä»¥è‰²åˆ—)"
emoji = "ğŸ‡®ğŸ‡±"

[[emoji]]
match = "(India|Mumbai|IND|å°åº¦|å­Ÿä¹°)"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "(Italy|Milan|æ„å¤§åˆ©|ç±³å…°)"
emoji = "ğŸ‡®ğŸ‡¹"

[[emoji]]
match = "(Japan|JPN|JP|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "(North.*?Korea|æœé²œ)"
emoji = "ğŸ‡°ğŸ‡µ"

[[emoji]]
match = "(Korea|KOR|KR|é¦–å°”|éŸ©|éŸ“)"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "(Macao|æ¾³é—¨|CTM)"
emoji = "ğŸ‡²ğŸ‡´"

[[emoji]]
match = "(Mexico|å¢¨è¥¿å“¥)"
emoji = "ğŸ‡²ğŸ‡½"

[[emoji]]
match = "(Malaysia|é©¬æ¥è¥¿äºš)"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "(Netherlands|NLD|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹)"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "(Philippines|è²å¾‹å®¾)"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "(Romania|POL|ç½—é©¬å°¼äºš)"
emoji = "ğŸ‡·ğŸ‡´"

[[emoji]]
match = "(Arabia|æ²™ç‰¹)"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emoji]]
match = "(Dubai|è¿ªæ‹œ)"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emoji]]
match = "(Sweden|DNK|ç‘å…¸)"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "(Thailand|æ³°å›½|æ›¼è°·)"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "(Turkey|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”)"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "(Vietnam|è¶Šå—)"
emoji = "ğŸ‡»ğŸ‡³"

[[emoji]]
match = "(Africa|å—é)"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emoji]]
match = "(?i:UK|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "(?i:SG|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "(?i:RU|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„)"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "(?i:US|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|é˜¿ä»€æœ¬)"
emoji = "ğŸ‡ºğŸ‡²"

[[emoji]]
match = "(?i:TW|Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°æ¹¾|[^-]å°|HINET)"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]æ¸¯)"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "(?i:CN|China|å›å›½|ä¸­å›½|æ±Ÿè‹|åŒ—äº¬|ä¸Šæµ·|å¹¿å·|æ·±åœ³|æ­å·|å¸¸å·|å¾å·|é’å²›|å®æ³¢|é•‡æ±Ÿ|æˆéƒ½|back)"
emoji = "ğŸ‡¨ğŸ‡³"
